worker_processes 1;
daemon off;
master_process off;
error_log /home/ubuntu/transparent-offload/transparent-runtime/apps/nginx-run/logs/error.log;
pid /home/ubuntu/transparent-offload/transparent-runtime/apps/nginx-run/logs/nginx.pid;
thread_pool default threads=32;
events { worker_connections 2048; }
http {
  access_log off;
  server {
    listen 7750;
    location /sync  { accel_sync;  }
    location /async { accel_async; }
  }
}
