worker_processes 2;
daemon off;
pid /home/ubuntu/transparent-offload/transparent-runtime/nginx-test/nginx.pid;
error_log /home/ubuntu/transparent-offload/transparent-runtime/nginx-test/logs/error.log;
events { worker_connections 1024; }
http {
  access_log off;
  client_body_temp_path /home/ubuntu/transparent-offload/transparent-runtime/nginx-test/logs/cbt;
  proxy_temp_path /home/ubuntu/transparent-offload/transparent-runtime/nginx-test/logs/pt;
  fastcgi_temp_path /home/ubuntu/transparent-offload/transparent-runtime/nginx-test/logs/ft;
  uwsgi_temp_path /home/ubuntu/transparent-offload/transparent-runtime/nginx-test/logs/ut;
  scgi_temp_path /home/ubuntu/transparent-offload/transparent-runtime/nginx-test/logs/st;
  server { listen 8088; location / { return 200 "transparent-runtime-ok\n"; } }
}
