ServerRoot /home/ubuntu/transparent-offload/transparent-runtime/apache-test
PidFile /home/ubuntu/transparent-offload/transparent-runtime/apache-test/httpd.pid
LoadModule mpm_worker_module /usr/lib/apache2/modules/mod_mpm_worker.so
LoadModule authz_core_module /usr/lib/apache2/modules/mod_authz_core.so
Listen 127.0.0.1:8190
ErrorLog /home/ubuntu/transparent-offload/transparent-runtime/apache-test/logs/err.log
<IfModule mpm_worker_module>
 StartServers 1
 ThreadsPerChild 8
</IfModule>
DocumentRoot /home/ubuntu/transparent-offload/transparent-runtime/apache-test
