[offload-engine]
spoe-agent offload-agent
    messages offload
    option var-prefix off
    option async
    option pipelining
    timeout hello      2s
    timeout idle       30s
    timeout processing 5s
    use-backend spoe-backend

spoe-message offload
    args ip=src
    event on-frontend-http-request
