#!/usr/bin/env bash
# Regenerate the self-signed TEST certificate for the nginx session-resumption
# test (referenced by nginx.conf as ssl_certificate / ssl_certificate_key).
# Throwaway localhost cert for local TLS tests only — never production.
set -euo pipefail
cd "$(dirname "$0")"

openssl req -x509 -newkey rsa:2048 -nodes \
  -keyout key.pem -out cert.pem -days 3650 -subj "/CN=localhost"

echo "wrote cert.pem key.pem"
# Note: sess.pem is a saved TLS session blob, produced at test time, e.g.:
#   openssl s_client -connect 127.0.0.1:<port> -sess_out sess.pem </dev/null
# then replayed with -sess_in to exercise resumption. It is a runtime artifact,
# not a credential, and is regenerated by the test run.
