foreground = yes
pid = /home/ubuntu/transparent-offload/transparent-runtime/sweep/stunnel.pid
[https]
accept = 7714
connect = 127.0.0.1:7713
cert = /home/ubuntu/transparent-offload/transparent-runtime/sweep/st.pem
