ServerName 127.0.0.1
Listen 7720
PidFile /home/ubuntu/transparent-offload/transparent-runtime/ap/httpd.pid
ErrorLog /home/ubuntu/transparent-offload/transparent-runtime/ap/logs/error.log
LoadModule mpm_worker_module /usr/lib/apache2/modules/mod_mpm_worker.so
LoadModule authz_core_module /usr/lib/apache2/modules/mod_authz_core.so
<IfModule mpm_worker_module>
  StartServers 1
  ServerLimit 1
  ThreadsPerChild 32
  MaxRequestWorkers 32
  MinSpareThreads 32
  MaxSpareThreads 32
</IfModule>
DocumentRoot /home/ubuntu/transparent-offload/transparent-runtime/ap/htdocs
<Directory /home/ubuntu/transparent-offload/transparent-runtime/ap/htdocs>
  Require all granted
</Directory>
